name: cartoon_weather
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.0-216.0.dev <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  json_annotation: ^4.8.0
  equatable: ^2.0.5
  http: ^0.13.5
  flutter_native_splash: ^2.2.17
  cupertino_icons: ^1.0.2
  charts_painter: ^3.0.0
  shared_preferences: ^2.0.17
  flutter_riverpod: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.0
  json_serializable: ^6.6.0
  test: ^1.22.2

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  fonts:
    - family:  CustomAppIcons
      fonts:
        - asset: assets/fonts/CustomAppIcons.ttf

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets: 
    - assets/images/
    - assets/fonts/